<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (student+)>
<!ELEMENT student (id, name, department)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
]>
<students>
  <student>
    <id>0123</id>
    <name>Basit</name>
    <department>IT</department>
  </student>
  <student>
    <id>0321</id>
    <name>Yousha</name>
    <department></department>
  </student>
</students>